const letters=[
 ['A','Apple','🍎'],['B','Ball','⚽'],['C','Cat','🐱'],['D','Dog','🐶'],['E','Elephant','🐘'],['F','Fish','🐟'],['G','Grapes','🍇'],['H','Hen','🐔'],['I','Ice Cream','🍦'],['J','Joker','🃏'],['K','Kite','🪁'],['L','Lion','🦁'],['M','Monkey','🐒'],['N','Nest','🪺'],['O','Orange','🍊'],['P','Parrot','🦜'],['Q','Queen','👑'],['R','Rose','🌹'],['S','Ship','🚢'],['T','Tiger','🐯'],['U','Umbrella','☂️'],['V','Van','🚐'],['W','Watch','⌚'],['X','Xmas Tree','🎄'],['Y','Yak','🐂'],['Z','Zebra','🦓']
];
const colours=[
 ['Red','Red','🔴'],['Blue','Blue','🔵'],['Yellow','Yellow','🟡'],['Green','Green','🟢'],['Orange','Orange','🟠'],['Purple','Purple','🟣'],['Pink','Pink','🩷'],['Brown','Brown','🟤'],['Black','Black','⚫'],['White','White','⚪']
];
const $=id=>document.getElementById(id);let index=0,mode='letters',soundOn=true,touchStartX=0,touchStartY=0;const card=$('card');
function currentItems(){return mode==='letters'?letters:colours}
function render(direction=0,speak=false){const items=currentItems();const [title,word,visual]=items[index];$('letter').textContent=mode==='letters'?title:title;$('visual').textContent=visual;$('phrase').textContent=mode==='letters'?`${title} for ${word}`:`${title} Colour`;$('progressLetter').textContent=title;$('progressCount').textContent=`${index+1} / ${items.length}`;$('progressBar').style.width=`${((index+1)/items.length)*100}%`;$('prevButton').disabled=index===0;$('nextButton').disabled=index===items.length-1;document.querySelectorAll('.letter-dot').forEach((b,i)=>b.classList.toggle('active',i===index));document.querySelector('.letter-dot.active')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});if(direction){card.classList.remove('enter-left','enter-right');void card.offsetWidth;card.classList.add(direction>0?'enter-right':'enter-left')}if(speak)speakPhrase()}
function speakPhrase(){if(!soundOn||!('speechSynthesis'in window))return;const items=currentItems();const [title,word]=items[index];window.speechSynthesis.cancel();const text=mode==='letters'?`${title} for ${word}`:`${title} colour`;const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.78;u.pitch=1.12;window.speechSynthesis.speak(u)}
function goTo(next){const items=currentItems();const newIndex=Math.max(0,Math.min(items.length-1,next));if(newIndex===index)return;const direction=newIndex>index?1:-1;index=newIndex;render(direction,$('autoPlay').checked)}
function buildNav(){const items=currentItems();$('letterNav').innerHTML='';items.forEach((item,i)=>{const b=document.createElement('button');b.className='letter-dot';b.type='button';b.textContent=item[0];b.setAttribute('aria-label',`Learn ${item[0]}`);b.addEventListener('click',()=>goTo(i));$('letterNav').appendChild(b)})}
$('prevButton').addEventListener('click',()=>goTo(index-1));$('nextButton').addEventListener('click',()=>goTo(index+1));$('listenButton').addEventListener('click',speakPhrase);
$('soundToggle').addEventListener('click',()=>{soundOn=!soundOn;if(!soundOn)window.speechSynthesis?.cancel();$('soundToggle').textContent=soundOn?'🔊':'🔇';$('soundToggle').setAttribute('aria-pressed',String(soundOn));$('soundToggle').setAttribute('aria-label',soundOn?'Turn sound off':'Turn sound on')});
$('autoPlay').addEventListener('change',()=>{if($('autoPlay').checked)speakPhrase()});
card.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStartX=t.clientX;touchStartY=t.clientY},{passive:true});card.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.2)goTo(index+(dx<0?1:-1))},{passive:true});
card.addEventListener('keydown',e=>{if(e.key==='ArrowRight')goTo(index+1);if(e.key==='ArrowLeft')goTo(index-1);if(e.key===' '||e.key==='Enter')speakPhrase()});
function switchMode(newMode){mode=newMode;index=0;buildNav();render()}
const modeBar=document.createElement('div');modeBar.className='mode-bar';modeBar.innerHTML='<button type="button" class="mode-button active" data-mode="letters">🔤 ABC</button><button type="button" class="mode-button" data-mode="colours">🎨 Colours</button>';$('letterNav').before(modeBar);modeBar.querySelectorAll('.mode-button').forEach(b=>b.addEventListener('click',()=>{modeBar.querySelectorAll('.mode-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');switchMode(b.dataset.mode)}));
buildNav();render();
