const DATA={
english:{
letters:[['A','Apple','🍎'],['B','Ball','⚽'],['C','Cat','🐱'],['D','Dog','🐶'],['E','Elephant','🐘'],['F','Fish','🐟'],['G','Grapes','🍇'],['H','Hen','🐔'],['I','Ice Cream','🍦'],['J','Joker','🃏'],['K','Kite','🪁'],['L','Lion','🦁'],['M','Monkey','🐒'],['N','Nest','🪺'],['O','Orange','🍊'],['P','Parrot','🦜'],['Q','Queen','👑'],['R','Rose','🌹'],['S','Sun','☀️'],['T','Tiger','🐯'],['U','Umbrella','☂️'],['V','Van','🚐'],['W','Watch','⌚'],['X','Xylophone','🎵'],['Y','Yak','🐂'],['Z','Zebra','🦓']],
numbers:[['1','One','1️⃣'],['2','Two','2️⃣'],['3','Three','3️⃣'],['4','Four','4️⃣'],['5','Five','5️⃣'],['6','Six','6️⃣'],['7','Seven','7️⃣'],['8','Eight','8️⃣'],['9','Nine','9️⃣'],['10','Ten','🔟'],['11','Eleven','1️⃣1️⃣'],['12','Twelve','1️⃣2️⃣'],['13','Thirteen','1️⃣3️⃣'],['14','Fourteen','1️⃣4️⃣'],['15','Fifteen','1️⃣5️⃣'],['16','Sixteen','1️⃣6️⃣'],['17','Seventeen','1️⃣7️⃣'],['18','Eighteen','1️⃣8️⃣'],['19','Nineteen','1️⃣9️⃣'],['20','Twenty','2️⃣0️⃣']],
colours:[['Red','Red','🔴'],['Blue','Blue','🔵'],['Yellow','Yellow','🟡'],['Green','Green','🟢'],['Orange','Orange','🟠'],['Purple','Purple','🟣'],['Pink','Pink','🩷'],['Brown','Brown','🟤'],['Black','Black','⚫'],['White','White','⚪']],
shapes:[['Circle','Circle','🔴'],['Square','Square','🟦'],['Triangle','Triangle','🔺'],['Rectangle','Rectangle','▭'],['Star','Star','⭐'],['Heart','Heart','❤️'],['Diamond','Diamond','🔶'],['Oval','Oval','🥚']],
animals:[['Cow','Cow','🐄'],['Buffalo','Buffalo','🐃'],['Dog','Dog','🐕'],['Cat','Cat','🐈'],['Horse','Horse','🐎'],['Elephant','Elephant','🐘'],['Lion','Lion','🦁'],['Tiger','Tiger','🐯'],['Monkey','Monkey','🐒'],['Rabbit','Rabbit','🐇'],['Peacock','Peacock','🦚'],['Parrot','Parrot','🦜']],
fruits:[['Apple','Apple','🍎'],['Mango','Mango','🥭'],['Banana','Banana','🍌'],['Orange','Orange','🍊'],['Grapes','Grapes','🍇'],['Watermelon','Watermelon','🍉'],['Guava','Guava','🍐'],['Papaya','Papaya','🧡'],['Pomegranate','Pomegranate','❤️'],['Coconut','Coconut','🥥']],
body:[['Eyes','Eyes','👀'],['Ears','Ears','👂'],['Nose','Nose','👃'],['Mouth','Mouth','👄'],['Teeth','Teeth','🦷'],['Hand','Hand','✋'],['Foot','Foot','🦶'],['Head','Head','🙂'],['Hair','Hair','💇'],['Heart','Heart','❤️']],
days:[['Monday','Monday','🌞'],['Tuesday','Tuesday','🌈'],['Wednesday','Wednesday','🌱'],['Thursday','Thursday','📚'],['Friday','Friday','🎨'],['Saturday','Saturday','⚽'],['Sunday','Sunday','👨‍👩‍👧‍👦']],
months:[['January','January','❄️'],['February','February','💗'],['March','March','🌸'],['April','April','🌦️'],['May','May','☀️'],['June','June','🌧️'],['July','July','🌧️'],['August','August','🇮🇳'],['September','September','📚'],['October','October','🪔'],['November','November','🍂'],['December','December','🎄']],
india:[['India','India','🇮🇳'],['National Flag','Tiranga','🇮🇳'],['Lotus','National Flower','🪷'],['Peacock','National Bird','🦚'],['Tiger','National Animal','🐅'],['Mango','National Fruit','🥭'],['Ganga','River Ganga','🌊'],['Himalayas','The Himalayas','🏔️']],
habits:[['Brush Teeth','Brush twice a day','🪥'],['Wash Hands','Wash hands with soap','🧼'],['Eat Healthy','Eat fruits and vegetables','🥦'],['Drink Water','Drink enough water','💧'],['Be Kind','Help and share','🤝'],['Read Daily','Read a little every day','📖'],['Play Outside','Run and play safely','⚽'],['Keep Clean','Put waste in the bin','🗑️']]},
hindi:{
hindi:[['अ','अनार','🍎'],['आ','आम','🥭'],['इ','इमली','🌿'],['ई','ईख','🎋'],['उ','उल्लू','🦉'],['ऊ','ऊन','🧶'],['ऋ','ऋषि','🧘'],['ए','एड़ी','🦶'],['ऐ','ऐनक','👓'],['ओ','ओखली','🥣'],['औ','औजार','🔧'],['अं','अंगूर','🍇'],['क','कमल','🪷'],['ख','खरगोश','🐇'],['ग','गमला','🪴'],['घ','घर','🏠'],['च','चम्मच','🥄'],['छ','छतरी','☂️'],['ज','जहाज','🚢'],['झ','झंडा','🚩'],['ट','टमाटर','🍅'],['ठ','ठेला','🛒'],['ड','डमरू','🥁'],['ढ','ढक्कन','🫙'],['ण','ण','🔤'],['त','तरबूज','🍉'],['थ','थर्मस','🧴'],['द','दूध','🥛'],['ध','धनुष','🏹'],['न','नल','🚰'],['प','पतंग','🪁'],['फ','फल','🍊'],['ब','बकरी','🐐'],['भ','भालू','🐻'],['म','मछली','🐟'],['य','योग','🧘‍♂️'],['र','रथ','🛺'],['ल','लट्टू','🪀'],['व','वन','🌳'],['श','शेर','🦁'],['ष','षट्कोण','⬡'],['स','सूरज','☀️'],['ह','हाथी','🐘'],['क्ष','क्षत्रिय','🛡️'],['त्र','त्रिशूल','🔱'],['ज्ञ','ज्ञान','📚']],
numbers:[['१','एक','1️⃣'],['२','दो','2️⃣'],['३','तीन','3️⃣'],['४','चार','4️⃣'],['५','पाँच','5️⃣'],['६','छह','6️⃣'],['७','सात','7️⃣'],['८','आठ','8️⃣'],['९','नौ','9️⃣'],['१०','दस','🔟'],['११','ग्यारह','1️⃣1️⃣'],['१२','बारह','1️⃣2️⃣'],['१३','तेरह','1️⃣3️⃣'],['१४','चौदह','1️⃣4️⃣'],['१५','पंद्रह','1️⃣5️⃣'],['१६','सोलह','1️⃣6️⃣'],['१७','सत्रह','1️⃣7️⃣'],['१८','अठारह','1️⃣8️⃣'],['१९','उन्नीस','1️⃣9️⃣'],['२०','बीस','2️⃣0️⃣']],
colours:[['लाल','लाल','🔴'],['नीला','नीला','🔵'],['पीला','पीला','🟡'],['हरा','हरा','🟢'],['नारंगी','नारंगी','🟠'],['बैंगनी','बैंगनी','🟣'],['गुलाबी','गुलाबी','🩷'],['भूरा','भूरा','🟤'],['काला','काला','⚫'],['सफेद','सफेद','⚪']],
shapes:[['वृत्त','वृत्त','🔴'],['वर्ग','वर्ग','🟦'],['त्रिभुज','त्रिभुज','🔺'],['आयत','आयत','▭'],['तारा','तारा','⭐'],['दिल','दिल','❤️'],['हीरा','हीरा','🔶'],['अंडाकार','अंडाकार','🥚']],
animals:[['गाय','गाय','🐄'],['भैंस','भैंस','🐃'],['कुत्ता','कुत्ता','🐕'],['बिल्ली','बिल्ली','🐈'],['घोड़ा','घोड़ा','🐎'],['हाथी','हाथी','🐘'],['शेर','शेर','🦁'],['बाघ','बाघ','🐯'],['बंदर','बंदर','🐒'],['खरगोश','खरगोश','🐇'],['मोर','मोर','🦚'],['तोता','तोता','🦜']],
fruits:[['सेब','सेब','🍎'],['आम','आम','🥭'],['केला','केला','🍌'],['संतरा','संतरा','🍊'],['अंगूर','अंगूर','🍇'],['तरबूज','तरबूज','🍉'],['अमरूद','अमरूद','🍐'],['पपीता','पपीता','🧡'],['अनार','अनार','❤️'],['नारियल','नारियल','🥥']],
habits:[['दाँत साफ करें','दिन में दो बार ब्रश करें','🪥'],['हाथ धोएँ','साबुन से हाथ धोएँ','🧼'],['पौष्टिक खाना','फल और सब्जियाँ खाएँ','🥦'],['पानी पिएँ','पर्याप्त पानी पिएँ','💧'],['दयालु बनें','मदद करें और बाँटें','🤝'],['रोज पढ़ें','हर दिन थोड़ा पढ़ें','📖'],['बाहर खेलें','सुरक्षित होकर खेलें','⚽'],['सफाई रखें','कूड़ा डिब्बे में डालें','🗑️']]}}
};
const POEMS={english:[['Twinkle Twinkle','⭐🌙',['Twinkle, twinkle, little star,','How I wonder what you are!','Up above the world so high,','Like a diamond in the sky.']],['Rain Rain','🌧️☔',['Rain, rain, come today,','Little drops are on their way.','Pitter-patter, soft and light,','Making gardens fresh and bright.']],['Brush Your Teeth','🪥😁',['Brush, brush, brush your teeth,','Up and down and underneath.','Morning time and bedtime too,','Clean white teeth are good for you!']],['Little Seed','🌱🌻',['Little seed beneath the ground,','Sleeping softly, safe and sound.','Sun and rain help you grow,','Up you reach, and flowers show!']],['Busy Bee','🐝🌼',['Busy bee goes buzz, buzz, buzz,','Flying round the flowers all day.','Collecting nectar as you go,','Making honey row by row!']],['Good Morning','🌞🐦',['Good morning, sunshine bright,','Good morning, birds in flight.','Wake up, smile and start the day,','Learn and play in every way!']]],hindi:[['मछली रानी','🐟🌊',['मछली रानी पानी में,','तैरे अपनी कहानी में।','छोटी पूँछ हिलाती जाए,','देखो कैसे मुस्काए!']],['बारिश आई','🌧️☔',['बारिश आई छम-छम-छम,','बूँदें आईं झम-झम-झम।','पेड़-पौधे सब खुश हो जाएँ,','चलो मिलकर गीत सुनाएँ।']],['सूरज दादा','🌞🌻',['सूरज दादा आए हैं,','किरणों संग मुस्काए हैं।','उठो बच्चों, खेलो-गाओ,','हर दिन कुछ नया सीख जाओ।']],['पेड़ लगाएँ','🌱🌳',['नन्हा पौधा आज लगाएँ,','मिलकर उसको पानी दें।','कल यह पेड़ बड़ा हो जाएगा,','सबको ठंडी छाया देगा।']]]};
const CATS={english:[['letters','🔤 ABC'],['numbers','🔢 Numbers'],['colours','🎨 Colours'],['shapes','🔷 Shapes'],['animals','🐾 Animals'],['fruits','🍎 Fruits'],['body','🧒 Body'],['days','📅 Days'],['months','🗓️ Months'],['india','🇮🇳 India'],['habits','💚 Good Habits'],['poems','📖 Poems'],['quiz','🎯 Quiz']],hindi:[['hindi','🔤 वर्णमाला'],['numbers','🔢 गिनती'],['colours','🎨 रंग'],['shapes','🔷 आकार'],['animals','🐾 जानवर'],['fruits','🍎 फल'],['habits','💚 अच्छी आदतें'],['poems','📖 कविताएँ'],['quiz','🎯 प्रश्नोत्तरी']]};
let language='english',mode='letters',index=0,soundOn=true,touchX=0,touchY=0;
function $(id){return document.getElementById(id)}
function items(){if(mode==='poems')return POEMS[language];if(mode==='quiz'){var base=language==='hindi'?DATA.hindi.hindi:DATA.english.letters;return base.slice(0,10).map(function(x,i){return {q:language==='hindi'?'यह '+x[0]+' से क्या है?':'What is '+x[0]+' for?',answer:x[1],visual:x[2],choices:[x[1],base[(i+2)%base.length][1],base[(i+4)%base.length][1]].sort(function(){return Math.random()-.5})}})}return DATA[language][mode]||[]}
function title(){var t={letters:'ABC Alphabet',numbers:language==='hindi'?'गिनती १–२०':'Numbers 1–20',colours:language==='hindi'?'रंग':'Colours',shapes:language==='hindi'?'आकार':'Shapes',animals:language==='hindi'?'जानवर':'Animals',fruits:language==='hindi'?'फल':'Fruits',body:'Body Parts',days:'Days of the Week',months:'Months of the Year',india:'India 🇮🇳',habits:language==='hindi'?'अच्छी आदतें':'Good Habits',poems:language==='hindi'?'हिंदी कविताएँ':'English Poems',hindi:'हिंदी वर्णमाला',quiz:language==='hindi'?'मज़ेदार प्रश्नोत्तरी':'Fun Quiz'};return t[mode]||mode}
function buildCategories(){var bar=$('categoryBar');bar.innerHTML='';CATS[language].forEach(function(c){var b=document.createElement('button');b.className='category-button';b.textContent=c[1];b.onclick=function(){switchMode(c[0])};bar.appendChild(b)})}
function buildNav(){var nav=$('letterNav');nav.innerHTML='';items().forEach(function(x,i){var b=document.createElement('button');b.className='letter-dot';b.textContent=mode==='poems'?'📖':mode==='quiz'?i+1:x[0];b.onclick=function(){index=i;render()};nav.appendChild(b)})}
function render(){var list=items();if(!list.length)return;if(index>=list.length)index=0;var x=list[index];$('pageTitle').textContent=title();$('progressLetter').textContent=mode==='poems'?'Poem '+(index+1):mode==='quiz'?'Q'+(index+1):x[0];$('progressCount').textContent=(index+1)+' / '+list.length;$('progressBar').style.width=((index+1)/list.length*100)+'%';document.querySelectorAll('.letter-dot').forEach(function(b,i){b.classList.toggle('active',i===index)});$('visual').hidden=false;$('letter').hidden=false;$('poemScene').hidden=true;$('poemLines').hidden=true;$('quizBox').hidden=true;$('listenButton').hidden=false;
if(mode==='poems'){var p=x;$('letter').textContent='📖';$('visual').textContent=p[1];$('phrase').textContent=p[0];$('hint').textContent=language==='hindi'?'कविता सुनो और साथ बोलो!':'Watch, listen and say it with me!';$('poemScene').hidden=false;$('poemScene').innerHTML=p[1].split('').map(function(e,i){return '<span style="--i:'+i+'">'+e+'</span>'}).join('');$('poemLines').hidden=false;$('poemLines').innerHTML=p[2].map(function(l,i){return '<div class="poem-line" style="animation-delay:'+(i*.08)+'s">'+l+'</div>'}).join('')}
else if(mode==='quiz'){var q=x;$('letter').textContent='🎯';$('visual').textContent=q.visual;$('phrase').textContent=q.q;$('hint').textContent=language==='hindi'?'सही उत्तर चुनो!':'Choose the correct answer!';$('quizBox').hidden=false;$('quizBox').innerHTML=q.choices.map(function(c){return '<button class="answer-button" type="button">'+c+'</button>'}).join('');$('quizBox').querySelectorAll('button').forEach(function(b){b.onclick=function(){var ok=b.textContent===q.answer;b.classList.add(ok?'correct':'wrong');$('hint').textContent=ok?(language==='hindi'?'🎉 शाबाश! सही उत्तर!':'🎉 Great! Correct!'):(language==='hindi'?'🙂 फिर कोशिश करो!':'🙂 Try again!');if(ok&&index<items().length-1)setTimeout(function(){index++;render()},650)}})}
else{$('letter').textContent=x[0];$('visual').textContent=x[2];if(mode==='letters'){$('phrase').textContent=x[0]+' for '+x[1];$('hint').textContent='Say it aloud with me!'}else if(mode==='hindi'){$('phrase').textContent=x[0]+' से '+x[1];$('hint').textContent='सुनो और मेरे साथ बोलो!'}else if(mode==='numbers'){$('phrase').textContent=x[0]+' — '+x[1];$('hint').textContent=language==='hindi'?'गिनो और बोलो!':'Count and say it!'}else{$('phrase').textContent=x[0];$('hint').textContent=x[1]}}
$('prevButton').disabled=index===0;$('nextButton').disabled=index===list.length-1;$('autoPlayLabel').textContent=mode==='poems'?'Auto-play poems':language==='hindi'?'हिंदी में Auto-play':'Auto-play lessons'}
function speak(){if(!soundOn||!window.speechSynthesis)return;var x=items()[index],text;if(mode==='poems')text=x[2].join(' ');else if(mode==='quiz')text=x.q;else if(mode==='letters')text=x[0]+' for '+x[1];else if(mode==='hindi')text=x[0]+', '+x[1];else text=x[0]+'. '+x[1];window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang=language==='hindi'?'hi-IN':'en-IN';u.rate=mode==='poems'?.7:.82;u.pitch=1.08;var voices=window.speechSynthesis.getVoices();var wanted=language==='hindi'?'hi-in':'en-in';var v=voices.find(function(a){return a.lang&&a.lang.toLowerCase()===wanted})||voices.find(function(a){return a.lang&&a.lang.toLowerCase().indexOf(language==='hindi'?'hi-':'en-')===0});if(v)u.voice=v;window.speechSynthesis.speak(u)}
function switchMode(m){mode=m;index=0;buildNav();render()}
function enterLanguage(l){language=l;mode=l==='hindi'?'hindi':'letters';index=0;$('languageHome').hidden=true;$('learningHome').hidden=false;buildCategories();buildNav();render()}
function goHome(){if(window.speechSynthesis)window.speechSynthesis.cancel();$('learningHome').hidden=true;$('languageHome').hidden=false}
function move(n){var list=items(),next=Math.max(0,Math.min(list.length-1,index+n));if(next!==index){index=next;render();if($('autoPlay').checked)setTimeout(speak,120)}}
function init(){ $('englishButton').onclick=function(){enterLanguage('english')};$('hindiButton').onclick=function(){enterLanguage('hindi')};$('homeButton').onclick=goHome;$('listenButton').onclick=speak;$('prevButton').onclick=function(){move(-1)};$('nextButton').onclick=function(){move(1)};$('soundToggle').onclick=function(){soundOn=!soundOn;if(!soundOn&&window.speechSynthesis)window.speechSynthesis.cancel();$('soundToggle').textContent=soundOn?'🔊':'🔇';$('soundToggle').setAttribute('aria-pressed',String(soundOn))};$('autoPlay').onchange=function(){if($('autoPlay').checked)speak()};var card=$('card');card.ontouchstart=function(e){touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY};card.ontouchend=function(e){var dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.2)move(dx<0?1:-1)};card.onkeydown=function(e){if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);if(e.key===' '||e.key==='Enter')speak()};buildCategories();buildNav();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();