const letters=[
 ['A','Apple','🍎'],['B','Ball','⚽'],['C','Cat','🐱'],['D','Dog','🐶'],['E','Elephant','🐘'],['F','Fish','🐟'],['G','Grapes','🍇'],['H','Hen','🐔'],['I','Ice Cream','🍦'],['J','Joker','🃏'],['K','Kite','🪁'],['L','Lion','🦁'],['M','Monkey','🐒'],['N','Nest','🪺'],['O','Orange','🍊'],['P','Parrot','🦜'],['Q','Queen','👑'],['R','Rose','🌹'],['S','Ship','🚢'],['T','Tiger','🐯'],['U','Umbrella','☂️'],['V','Van','🚐'],['W','Watch','⌚'],['X','Xmas Tree','🎄'],['Y','Yak','🐂'],['Z','Zebra','🦓']
];
const colours=[['Red','Red','🔴'],['Blue','Blue','🔵'],['Yellow','Yellow','🟡'],['Green','Green','🟢'],['Orange','Orange','🟠'],['Purple','Purple','🟣'],['Pink','Pink','🩷'],['Brown','Brown','🟤'],['Black','Black','⚫'],['White','White','⚪']];
const hindi=[
 ['अ','अनार','🍎'],['आ','आम','🥭'],['इ','इमली','🌿'],['ई','ईख','🎋'],['उ','उल्लू','🦉'],['ऊ','ऊन','🧶'],['ऋ','ऋषि','🧘'],['ए','एड़ी','🦶'],['ऐ','ऐनक','👓'],['ओ','ओखली','🥣'],['औ','औजार','🔧'],['अं','अंगूर','🍇'],['अः','अः','✨'],['क','कमल','🪷'],['ख','खरगोश','🐇'],['ग','गमला','🪴'],['घ','घर','🏠'],['ङ','ङ','🔤'],['च','चम्मच','🥄'],['छ','छतरी','☂️'],['ज','जहाज','🚢'],['झ','झंडा','🚩'],['ञ','ञ','🔤'],['ट','टमाटर','🍅'],['ठ','ठेला','🛒'],['ड','डमरू','🥁'],['ढ','ढक्कन','🫙'],['ण','ण','🔤'],['त','तरबूज','🍉'],['थ','थर्मस','🧴'],['द','दूध','🥛'],['ध','धनुष','🏹'],['न','नल','🚰'],['प','पतंग','🪁'],['फ','फल','🍊'],['ब','बकरी','🐐'],['भ','भालू','🐻'],['म','मछली','🐟'],['य','योग','🧘‍♂️'],['र','रथ','🛺'],['ल','लट्टू','🪀'],['व','वन','🌳'],['श','शेर','🦁'],['ष','षट्कोण','⬡'],['स','सूरज','☀️'],['ह','हाथी','🐘'],['क्ष','क्षत्रिय','🛡️'],['त्र','त्रिशूल','🔱'],['ज्ञ','ज्ञान','📚']
];
const poems=[
 {title:'Twinkle Twinkle',visual:'⭐🌙',lines:['Twinkle, twinkle, little star,','How I wonder what you are!','Up above the world so high,','Like a diamond in the sky.'],scene:['🌙','⭐','✨','⭐','✨']},
 {title:'Rain Rain',visual:'🌧️☔',lines:['Rain, rain, come today,','Little drops are on their way.','Pitter-patter, soft and light,','Making gardens fresh and bright.'],scene:['☁️','💧','💧','☔','🌱']},
 {title:'Little Butterfly',visual:'🦋🌸',lines:['Little butterfly, fly so free,','Dance around the flower tree.','Red and yellow, blue and green,','Prettiest wings I have ever seen!'],scene:['🌸','🦋','🌼','🦋','🌺']},
 {title:'Five Little Ducks',visual:'🦆🦆🦆',lines:['Five little ducks went out one day,','Over the hills and far away.','Mother duck said, “Quack, quack, quack!”','And all five little ducks came back.'],scene:['🦆','🦆','🦆','🏞️','🦆🦆']},
 {title:'Good Morning',visual:'🌞🐦🌼',lines:['Good morning, sunshine bright,','Good morning, birds in flight.','Wake up, smile and start the day,','Learn and play in every way!'],scene:['🌅','🌞','🐦','🌼','😊']},
 {title:'Brush Your Teeth',visual:'🪥😁',lines:['Brush, brush, brush your teeth,','Up and down and underneath.','Morning time and bedtime too,','Clean white teeth are good for you!'],scene:['😁','🪥','🦷','✨','😁']},
 {title:'Little Seed',visual:'🌱🌻',lines:['Little seed beneath the ground,','Sleeping softly, safe and sound.','Sun and rain help you grow,','Up you reach, and flowers show!'],scene:['🌰','🌱','☀️','💧','🌻']},
 {title:'The Busy Bee',visual:'🐝🌼',lines:['Busy bee goes buzz, buzz, buzz,','Flying round the flowers does.','Collecting nectar all day long,','Buzzing to a happy song!'],scene:['🐝','🌼','🐝','🌻','🍯']}
];
const $=id=>document.getElementById(id);let index=0,mode='letters',language='english',soundOn=true,touchStartX=0,touchStartY=0;const card=$('card');
function currentItems(){return mode==='letters'?letters:mode==='colours'?colours:mode==='hindi'?hindi:poems}
function enterLanguage(lang){language=lang;$('languageHome').hidden=true;$('learningHome').hidden=false;$('pageTitle').textContent=lang==='hindi'?'हिंदी सीखें 🇮🇳':'English Learning 🇬🇧';mode=lang==='hindi'?'hindi':'letters';index=0;buildNav();document.querySelectorAll('.mode-button').forEach(b=>b.hidden=lang==='hindi'?(b.dataset.mode!=='hindi'&&b.dataset.mode!=='poems'):(b.dataset.mode==='hindi'));document.querySelectorAll('.mode-button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('autoPlayLabel').textContent=lang==='hindi'?'हिंदी अक्षर Auto-play':'Auto-play lessons';render()}
function goHome(){window.speechSynthesis?.cancel();$('learningHome').hidden=true;$('languageHome').hidden=false}
function render(direction=0,speak=false){const items=currentItems();const item=items[index];const [title,word,visual]=mode==='poems'?[item.title,'',item.visual]:item;$('letter').textContent=mode==='poems'?'📖':title;$('visual').textContent=visual;$('phrase').textContent=mode==='letters'?`${title} for ${word}`:mode==='colours'?`${title} Colour`:mode==='hindi'?`${title} से ${word}`:item.title;$('hint').textContent=mode==='poems'?'Watch the little story and listen!':mode==='hindi'?'सुनो और बोलो मेरे साथ!':mode==='letters'?'Tap listen and say it with me!':'Listen and learn the colour!';$('progressLetter').textContent=mode==='poems'?`Poem ${index+1}`:title;$('progressCount').textContent=`${index+1} / ${items.length}`;$('progressBar').style.width=`${((index+1)/items.length)*100}%`;$('prevButton').disabled=index===0;$('nextButton').disabled=index===items.length-1;document.querySelectorAll('.letter-dot').forEach((b,i)=>b.classList.toggle('active',i===index));document.querySelector('.letter-dot.active')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});const poemBox=$('poemLines');poemBox.innerHTML='';if(mode==='poems'){poemBox.hidden=false;item.lines.forEach((line,i)=>{const p=document.createElement('div');p.className='poem-line';p.textContent=line;p.style.animationDelay=`${i*.08}s`;poemBox.appendChild(p)});const scene=$('poemScene');scene.hidden=false;scene.innerHTML=item.scene.map((x,i)=>`<span style="--i:${i}">${x}</span>`).join('')}else{poemBox.hidden=true;$('poemScene').hidden=true}if(direction){card.classList.remove('enter-left','enter-right');void card.offsetWidth;card.classList.add(direction>0?'enter-right':'enter-left')}if(speak)speakPhrase()}
function speakPhrase(){if(!soundOn||!('speechSynthesis'in window))return;const items=currentItems();const item=items[index];let text;if(mode==='letters')text=`${item[0]} for ${item[1]}`;else if(mode==='colours')text=`${item[0]} colour`;else if(mode==='hindi')text=`${item[0]}. ${item[1]}`;else text=item.lines.join(' ');window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=mode==='hindi'?'hi-IN':'en-IN';u.rate=mode==='poems'?.68:.78;u.pitch=1.08;const voices=window.speechSynthesis.getVoices();const preferred=mode==='hindi'?voices.find(v=>v.lang?.toLowerCase()==='hi-in')||voices.find(v=>v.lang?.toLowerCase().startsWith('hi-in')):voices.find(v=>v.lang?.toLowerCase()==='en-in')||voices.find(v=>v.lang?.toLowerCase().startsWith('en-in'));if(preferred)u.voice=preferred;window.speechSynthesis.speak(u)}
function goTo(next){const items=currentItems();const newIndex=Math.max(0,Math.min(items.length-1,next));if(newIndex===index)return;const direction=newIndex>index?1:-1;index=newIndex;render(direction,$('autoPlay').checked)}
function buildNav(){const items=currentItems();$('letterNav').innerHTML='';items.forEach((item,i)=>{const b=document.createElement('button');b.className='letter-dot';b.type='button';b.textContent=mode==='poems'?'📖':item[0];b.setAttribute('aria-label',mode==='poems'?`Learn ${item.title}`:`Learn ${item[0]}`);b.addEventListener('click',()=>goTo(i));$('letterNav').appendChild(b)})}
$('englishButton').addEventListener('click',()=>enterLanguage('english'));$('hindiButton').addEventListener('click',()=>enterLanguage('hindi'));$('homeButton').addEventListener('click',goHome);$('prevButton').addEventListener('click',()=>goTo(index-1));$('nextButton').addEventListener('click',()=>goTo(index+1));$('listenButton').addEventListener('click',speakPhrase);
$('soundToggle').addEventListener('click',()=>{soundOn=!soundOn;if(!soundOn)window.speechSynthesis?.cancel();$('soundToggle').textContent=soundOn?'🔊':'🔇';$('soundToggle').setAttribute('aria-pressed',String(soundOn));$('soundToggle').setAttribute('aria-label',soundOn?'Turn sound off':'Turn sound on')});$('autoPlay').addEventListener('change',()=>{if($('autoPlay').checked)speakPhrase()});
card.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStartX=t.clientX;touchStartY=t.clientY},{passive:true});card.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.2)goTo(index+(dx<0?1:-1))},{passive:true});card.addEventListener('keydown',e=>{if(e.key==='ArrowRight')goTo(index+1);if(e.key==='ArrowLeft')goTo(index-1);if(e.key===' '||e.key==='Enter')speakPhrase()});
function switchMode(newMode){mode=newMode;index=0;buildNav();$('autoPlayLabel').textContent=mode==='poems'?'Auto-play poems':mode==='hindi'?'हिंदी अक्षर Auto-play':'Auto-play lessons';render()}
const modeBar=document.createElement('div');modeBar.className='mode-bar';modeBar.innerHTML='<button type="button" class="mode-button active" data-mode="letters">🔤 ABC</button><button type="button" class="mode-button" data-mode="colours">🎨 Colours</button><button type="button" class="mode-button" data-mode="poems">📖 Poems</button><button type="button" class="mode-button" data-mode="hindi">🇮🇳 हिंदी</button>';$('letterNav').before(modeBar);modeBar.querySelectorAll('.mode-button').forEach(b=>b.addEventListener('click',()=>{if(b.hidden)return;modeBar.querySelectorAll('.mode-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');switchMode(b.dataset.mode)}));
buildNav();render();
